image: 192.168.1.211:5000/jekyll

stages:
  - build
  - deploy

build:
  stage: build
  script: jekyll build
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_BUILD_TAG}"
    paths:
    - public/
    expire_in: 2 weeks
  only:
    - caitong-financial-product

deploy:
  stage: deploy
  script:
    - find public -type f -exec curl --ftp-create-dirs -T {} -u $FTP_USER:$FTP_PASSWORD ftp://192.168.1.211/caitong-financial-product/{} \;
  only:
    - caitong-financial-product
